### ISSUE TITLE
unknownfieldexception

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [esensar/kotlinx-serialization-msgpack#69]
Hello 
Thank you for useful library
I want to  use feature `ignoreUnknownKeys = true`  
when using `MsgPack.decodeFromByteArray`  , I get an error  `unknownfieldexception`

**Comment by esensar** [comment]
This is a missing feature actually, I will try to make a 0.4.4 release including it.

**Comment by AlirezaGhanbarinia** [comment]
thank you @esensar  🙏
