### ISSUE TITLE
Crashing due to integer deserialization

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [esensar/kotlinx-serialization-msgpack#73]
As we use Go lang in server-side, we provides two type for integer considered as int32 (which is 4 bytes) and int64 (which is 8 bytes). 
I declared a custom deserializer and inside it I used try-catch to handle any exception but when deserialization, an exception is thrown and the source of the exception is the model class.

**Comment by esensar** [comment]
Could you give more information, or an example of payload?
Part of stacktrace related to the library would be useful too. Thanks!

**Comment by esensar** [comment]
You can also try using 0.5.0 snapshot, which has more descriptive errors. I plan on releasing 0.5.0 soon to make that feature available.
