### ISSUE TITLE
iOS Simulator not supported

### ISSUE THREAD

**Issue by androideo** [esensar/kotlinx-serialization-msgpack#77]
**Version**
 - Library version: 0.5.1
 - Platform info: iosSimulatorArm64

**Describe the bug**
I have imported *build.gradle.kts* the kotlin-targets **iosX64()** and ** iosArm64()**, when I build everything works fine. As soon as I use **iosSimulatorArm64()** the build crashes and it tells me:

> Could not resolve com.ensarsarajcic.kotlinx:serialization-msgpack:0.5.1

**Expected behavior**
I want to be able to execute a build with **iosSimulatorArm64()**

**Comment by esensar** [comment]
Thank you for reporting this. It should be an easy fix.

**Comment by FabD86** [comment]
PR for iosSimulatorArm64 #78
Build and tests did run just fine.

**Comment by esensar** [comment]
@FabD86 
Thank you for your contribution. #78 has been merged and released in 0.5.2
