### ISSUE TITLE
double serialization in BaseMsgPackExtensionSerializer

### ISSUE THREAD

**Issue by krisbitney** [esensar/kotlinx-serialization-msgpack#92]
The `serialize` method in `BaseMsgPackExtensionSerializer` serializes the value twice.

```kotlin
    override fun serialize(encoder: Encoder, value: T) {
        val extension = serialize(value) // FIRST SERIALIZATION
        if (checkTypeId && extension.extTypeId != extTypeId) {
            throw MsgPackSerializationException.extensionSerializationWrongType(extension, extTypeId, extension.extTypeId)
        }
        encoder.encodeSerializableValue(serializer, serialize(value)) // SECOND SERIALIZATION
    }
```

I tried to create a PR but got an "access denied" error.

**Comment by esensar** [comment]
Thank you for reporting this!

To open a PR, you need to fork the repo: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

I will gladly accept your PR with this fix!
